# Generated by Django 5.1.5 on 2025-01-28 09:33

import FoodApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=FoodApp.models.get_image_path),
        ),
    ]
